stages:
  - test
  - build
  - deploy

javascript:
  stage: test
  script:
    - "jest --ci --reporters=default --reporters=jest-junit"
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

build:
  image: node:latest # Run the job in a `node` docker image
  stage: build
  script:
    - yarn install # Run `yarn install` and `yarn build`
    - yarn build
  artifacts:
    paths:
      - build/ # Save the build result as an artifact

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
