export default [
  {
    id: 1,
    symbol: "SNAP",
    name: "Snap Inc",
    price: "$10",
    change: "$1",
    volume: "54 M",
    average: "44.9 M",
    capital: "18.6B",
    ratio: "N/A",
  },
  {
    id: 2,
    symbol: "TWTR",
    name: "Twitter Inc.",
    price: "$10",
    change: "$2",
    volume: "54 M",
    average: "74.9 M",
    capital: "18.6B",
    ratio: "N/A",
  },
  {
    id: 3,
    symbol: "AAPL",
    name: "Apple Inc.",
    price: "$221",
    change: "$3",
    volume: "154 M",
    average: "44.9 M",
    capital: "18.6B",
    ratio: "N/A",
  },
  {
    id: 4,
    symbol: "MSFT",
    name: "Microsoft Cooperation",
    price: "$140",
    change: "$4",
    volume: "124 M",
    average: "44.9 M",
    capital: "20.6B",
    ratio: "N/A",
  },
  {
    id: 5,
    symbol: "OTHER",
    name: "Other Inc",
    price: "$10",
    change: "$5",
    volume: "34 M",
    average: "44.9 M",
    capital: "18.6B",
    ratio: "N/A",
  },
  {
    id: 6,
    symbol: "IBM",
    name: "IBM Inc",
    price: "$72",
    change: "$6",
    volume: "66 M",
    average: "48.9 M",
    capital: "10.6B",
    ratio: "N/A",
  },
  {
    id: 7,
    symbol: "Facebook",
    name: "Facebook Inc",
    price: "$172",
    change: "$7",
    volume: "166 M",
    average: "148.9 M",
    capital: "21.6B",
    ratio: "N/A",
  },
];
